project:
  type: website
  output-dir: docs
  
website:
  title: "Emma Bea Mitchell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      

format:
  html:
    theme: vapor
    css: styles.css
    toc: false
    page-layout: full



